# Generated by Django 3.1.3 on 2020-12-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_of_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_address', models.CharField(max_length=200)),
                ('seller_city', models.CharField(max_length=200)),
                ('seller_state', models.CharField(max_length=200)),
                ('seller_zip', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_city', models.CharField(max_length=200)),
                ('buyer_state', models.CharField(max_length=200)),
                ('buyer_zip', models.CharField(max_length=5)),
                ('properties', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.bill_of_sale')),
            ],
        ),
    ]
