# Generated by Django 3.1.3 on 2020-12-28 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_bill_of_sale_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='Document name', max_length=20)),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('seller_address', models.CharField(blank=True, max_length=200)),
                ('seller_city', models.CharField(blank=True, max_length=200)),
                ('seller_state', models.CharField(blank=True, max_length=200)),
                ('seller_zip', models.CharField(blank=True, max_length=200)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_address', models.CharField(blank=True, max_length=200)),
                ('buyer_city', models.CharField(blank=True, max_length=200)),
                ('buyer_state', models.CharField(blank=True, max_length=200)),
                ('buyer_zip', models.CharField(blank=True, max_length=5)),
                ('properties', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='bill_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.billofsale'),
        ),
        migrations.DeleteModel(
            name='Bill_of_sale',
        ),
    ]
