# Generated by Django 3.1.3 on 2020-12-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20201228_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
