# Generated by Django 3.1.3 on 2020-12-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_auto_20201230_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofsale',
            name='seller_state',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=200, verbose_name='State'),
        ),
    ]
