# Generated by Django 3.1.3 on 2021-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0011_auto_20201230_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='bill_of_sale',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('', 'empty'), ('bill_of_sale', 'Bill of Sale'), ('articles_of_incorporation', 'Articles of Incorporation')], default='', max_length=200, verbose_name='Name'),
        ),
    ]
