# Generated by Django 3.1.3 on 2021-02-10 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_auto_20210202_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('', 'empty'), ('bill_of_sale', 'Bill of Sale'), ('articles_of_incorporation', 'Articles of Incorporation')], default='', max_length=200, verbose_name='Document Type'),
        ),
    ]
