# Generated by Django 3.1.3 on 2021-02-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_auto_20210209_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date',
            new_name='doc_date',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_name',
            field=models.CharField(default='Document name', max_length=20),
        ),
    ]
