# Generated by Django 3.1.3 on 2020-12-22 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_of_sale',
            name='date',
        ),
        migrations.AddField(
            model_name='bill_of_sale',
            name='document_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill_of_sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
