# Generated by Django 3.1.3 on 2020-12-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_billofsale_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofsale',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
