# Generated by Django 3.1.3 on 2020-12-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_auto_20201230_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofsale',
            name='price2',
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='buyer_state',
            field=models.CharField(blank=True, max_length=200, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='buyer_zip',
            field=models.CharField(blank=True, max_length=5, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='seller_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='seller_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='seller_state',
            field=models.CharField(blank=True, max_length=200, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='seller_zip',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zip'),
        ),
    ]
